AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 create

Parameters: 
  NameBase: 
    Description: this is base name.
    Type: String
    Default: lecture10

  KeyName:
    Description: The name of the EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
    Default: KEY1
  
  MyCidrIp:
    Description: IP address allowed to access EC2
    Type: String
    Default: 133.106.194.106/32

Resources:
  EC2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-00d101850e971728d
      KeyName: !Ref KeyName
      InstanceType: t2.medium
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: subnet-069b497c8557d7e9b
          GroupSet:
            - !Ref EC2SG
      Tags:
          - Key: Name
            Value: lecture10-ec2-a-cf

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: lecture10-ec2-sg-cf
      GroupDescription: Allow SSH and HTTP access only MyIP
      VpcId: vpc-042638713c67febb6
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyCidrIp

Outputs:
  EC2PublicIP:
    Value: !GetAtt EC2.PublicIp
    Description: Public IP of EC2 instance