AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 create

Parameters: 
  NameBase: 
    Description: this is base name.
    Type: String
    Default: lecture10
    
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
  
  MyIP:
    Description: IP address allowed to access EC2
    Type: String

Resources:
  EC2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-00d101850e971728d
      KeyName: !Ref KeyName
      InstanceType: t2.medium
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue lecture10-vpc-PublicSubnet1Id
          GroupSet:
            - !Ref EC2SG
      Tags:
          - Key: Name
            Value: !sub ${NameBase}-ec2-a-cf

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !sub ${NameBase}-ec2-sg-cf
      GroupDescription: Allow SSH and HTTP access only MyIP
      VpcId: !ImportValue lecture10-vpc-VPCId
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref MyIP
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP

Outputs:
  EC2PublicIP:
    Value: !GetAtt EC2.PublicIp
    Description: Public IP of EC2 instance